### ISSUE TITLE
请问efi文件嘞

### ISSUE THREAD

**Issue by tonylu110** [tzxfwan/dell-5577-oc#1]
请问efi文件嘞

**Comment by tzxfwan** [comment]
邮箱发我



---原始邮件---
发件人: "Anthony ***@***.***&gt;
发送时间: 2022年6月29日(周三) 晚上11:01
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [tzxfwan/dell-5577-oc] 请问efi文件嘞 (Issue #1)




 
请问efi文件嘞

**Comment by tonylu110** [comment]
luxiaoyu20020518@hotmail.com

**Comment by tonylu110** [comment]
请问您发了吗

**Comment by tzxfwan** [comment]
今天晚上吧，我一直没回家，不好意思



---原始邮件---
发件人: "Anthony ***@***.***&gt;
发送时间: 2022年7月1日(周五) 中午12:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tzxfwan/dell-5577-oc] 请问efi文件嘞 (Issue #1)




 
请问您发了吗
